language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t bnagaraja9099/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true bnagaraja9099/docker-react npm run test
after_success:
    - docker build -t bnagaraja9099/frontend .
    # Login to Docker Cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # take and push images
    - docker push bnagaraja9099/frontend

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-1-721660988087
  bucket_path: docker-react
  'on':
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
